services:
  ws:
    build:
      context: .
      dockerfile: ./apps/ws/Dockerfile
      args:
        JWT_SECRET: ${JWT_SECRET}
    image: myapp-ws:latest
    environment:
      NODE_ENV: production
      WS_PORT: "8080"
      WS_PATH: "/graphql"
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: postgres://app:app@postgres:5432/appdb
      JWT_SECRET: ${JWT_SECRET}
    # ports:
    #   - "8081:8080"
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_GRAPHQL_HTTP: ${NEXT_PUBLIC_GRAPHQL_HTTP}
        NEXT_PUBLIC_GRAPHQL_WS: ${NEXT_PUBLIC_GRAPHQL_WS}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}

        NEXT_PUBLIC_FACEBOOK_APP_ID: ${NEXT_PUBLIC_FACEBOOK_APP_ID}
        NEXT_PUBLIC_FACEBOOK_APP_SECRET: ${NEXT_PUBLIC_FACEBOOK_APP_SECRET}
        NEXT_PUBLIC_SENDGRID_API_KEY: ${NEXT_PUBLIC_SENDGRID_API_KEY}
        NEXT_PUBLIC_SENDGRID_FROM_EMAIL: ${NEXT_PUBLIC_SENDGRID_FROM_EMAIL}
        NEXT_PUBLIC_SUPPORT_URL: ${NEXT_PUBLIC_SUPPORT_URL}
        NEXT_PUBLIC_SUPPORT_TO_EMAIL: ${NEXT_PUBLIC_SUPPORT_TO_EMAIL}
        COOKIE_SECURE: ${COOKIE_SECURE} 
        WEB_NAME: ${WEB_NAME}

        FB_PAGE_ID: ${FB_PAGE_ID}
        FB_PAGE_ACCESS_TOKEN: ${FB_PAGE_ACCESS_TOKEN}
        SOCIAL_QUEUE_KEY: ${SOCIAL_QUEUE_KEY}
        SOCIAL_DLQ_KEY: ${SOCIAL_DLQ_KEY}
        SOCIAL_DELAYED_KEY: ${SOCIAL_DELAYED_KEY}
        ADMIN_TOKEN: ${ADMIN_TOKEN}
        JWT_SECRET: ${JWT_SECRET}
    image: myapp-web:latest
    environment:
      NODE_ENV: production
      WEB_NAME: ${WEB_NAME}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      NEXT_PUBLIC_GRAPHQL_HTTP: ${NEXT_PUBLIC_GRAPHQL_HTTP}
      NEXT_PUBLIC_GRAPHQL_WS: ${NEXT_PUBLIC_GRAPHQL_WS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      STORAGE_DIR: /app/storage
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}

      NEXT_PUBLIC_FACEBOOK_APP_ID: ${NEXT_PUBLIC_FACEBOOK_APP_ID}
      NEXT_PUBLIC_FACEBOOK_APP_SECRET: ${NEXT_PUBLIC_FACEBOOK_APP_SECRET}
      NEXT_PUBLIC_SENDGRID_API_KEY: ${NEXT_PUBLIC_SENDGRID_API_KEY}
      NEXT_PUBLIC_SENDGRID_FROM_EMAIL: ${NEXT_PUBLIC_SENDGRID_FROM_EMAIL}
      NEXT_PUBLIC_SUPPORT_URL: ${NEXT_PUBLIC_SUPPORT_URL}
      NEXT_PUBLIC_SUPPORT_TO_EMAIL: ${NEXT_PUBLIC_SUPPORT_TO_EMAIL}

      COOKIE_SECURE: ${COOKIE_SECURE}

      FB_PAGE_ID: ${FB_PAGE_ID}
      FB_PAGE_ACCESS_TOKEN: ${FB_PAGE_ACCESS_TOKEN}
      SOCIAL_QUEUE_KEY: ${SOCIAL_QUEUE_KEY}
      SOCIAL_DLQ_KEY: ${SOCIAL_DLQ_KEY}
      SOCIAL_DELAYED_KEY: ${SOCIAL_DELAYED_KEY}
      ADMIN_TOKEN: ${ADMIN_TOKEN}

      JWT_SECRET: ${JWT_SECRET}
      
    # ports:
    #   - "80:3000"   # üëà prod ‡πÉ‡∏ä‡πâ port 80 ‡∏î‡πâ‡∏≤‡∏ô‡∏ô‡∏≠‡∏Å
    depends_on:
      - postgres
      - redis
      - ws
    volumes:
      - ./storage:/app/storage
      # - /mnt/volume_sgp1_01/storage:/app/storage

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/web/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./apps/web/certs:/certs:ro
      - caddy_data:/data
      - caddy_config:/config

  social-worker:
    image: myapp-web:latest
    working_dir: /app/apps/web
    command: ["node", "scripts/social-worker.mjs"]
    environment:
      NODE_ENV: development
      REDIS_URL: ${REDIS_URL}

      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      FB_PAGE_ID: ${FB_PAGE_ID}
      FB_PAGE_ACCESS_TOKEN: ${FB_PAGE_ACCESS_TOKEN}
      SOCIAL_QUEUE_KEY: ${SOCIAL_QUEUE_KEY}
      SOCIAL_DLQ_KEY: ${SOCIAL_DLQ_KEY}
      SOCIAL_DELAYED_KEY: ${SOCIAL_DELAYED_KEY}
    volumes:
      # - ./:/app
      - ./storage:/app/storage
    depends_on:
      - web
      - postgres
      - redis
    restart: unless-stopped
