services:
  ws:
    build:
      context: .
      dockerfile: ./apps/ws/Dockerfile
    image: myapp-ws:latest
    environment:
      NODE_ENV: production
      WS_PORT: "8080"
      WS_PATH: "/graphql"
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: postgres://app:app@postgres:5432/appdb
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_GRAPHQL_HTTP: ${NEXT_PUBLIC_GRAPHQL_HTTP}
        NEXT_PUBLIC_GRAPHQL_WS: ${NEXT_PUBLIC_GRAPHQL_WS}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        COOKIE_SECURE: ${COOKIE_SECURE} 
        WEB_NAME: ${WEB_NAME}
    image: myapp-web:latest
    environment:
      NODE_ENV: production
      WEB_NAME: ${WEB_NAME}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      NEXT_PUBLIC_GRAPHQL_HTTP: ${NEXT_PUBLIC_GRAPHQL_HTTP}
      NEXT_PUBLIC_GRAPHQL_WS: ${NEXT_PUBLIC_GRAPHQL_WS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      STORAGE_DIR: /app/storage
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      COOKIE_SECURE: ${COOKIE_SECURE}
    ports:
      - "80:3000"   # üëà prod ‡πÉ‡∏ä‡πâ port 80 ‡∏î‡πâ‡∏≤‡∏ô‡∏ô‡∏≠‡∏Å
    depends_on:
      - postgres
      - redis
      - ws
    volumes:
      - ./storage:/app/storage
